alternate: Lin's Blog 

loader:
  start: true # å½“åˆæ¬¡æ‰“å¼€é¡µé¢æ—¶ï¼Œæ˜¾ç¤ºåŠ è½½åŠ¨ç”»
  switch: false # tab åˆ‡æ¢åˆ°å…¶ä»–é¡µé¢æ—¶ï¼Œæ˜¾ç¤ºåŠ è½½åŠ¨ç”»

menu:
  home: / || home
  posts:
    default: / || feather
    archives: /archives/ || list-alt
    categories: /categories/ || th
    tags: /tags/ || tags
  
  # ç¦»å¥‡bug
  # å¾®è¨€: /shuoshuo/ || comments
  ä¹¦å•: /books || books
  å‹é“¾: /friends/ || heart
  about: /about/ || user
  # links: /links/ || magic

social:
  github: https://github.com/shuilinzi || github || "#191717"
  bilibili: https://space.bilibili.com/351888750 || bilibili || "#fb7299"
  #google: https://plus.google.com/yourname || google
  # twitter: https://twitter.com/yourname || twitter || "#00aff0"
  # zhihu: https://www.zhihu.com/people/yourname || zhihu || "#1e88e5"
  # music: https://music.163.com/#/user/home?id=yourid || cloud-music || "#e60026"
  # weibo: https://weibo.com/yourname || weibo || "#ea716e"
  # about: https://about.me/yourname || address-card || "#3b5998"
  email: mailto:shuilinzi@qq.com || envelope || "#55acd5"
  #facebook: https://www.facebook.com/yourname || facebook
  #stackoverflow: https://stackoverflow.com/yourname || stack-overflow
  #youtube: https://youtube.com/yourname || youtube
  #instagram: https://instagram.com/yourname || instagram
  #skype: skype:yourname?call|chat || skype
  #douban: https://www.douban.com/people/yourname/ || douban

font:
  enable: true
  # Font options:
  # `external: true` will load this font family from `host` above.
  # `family: Times New Roman`. Without any quotes.
  # `size: x.x`. Use `em` as unit. Default: 1 (16px)

  # Global font settings used for all elements inside <body>.
  global:
    external: true
    family: Noto Serif SC


  # Font settings for alternate title.
  logo:
    external: true
    family: Fredericka the Great
    size: 3.5

  # Font settings for site title.
  title:
    external: true
    family: Noto Serif JP
    size: 2.5

  # Font settings for headlines (<h1> to <h6>).
  headings:
    external: true
    family: Noto Serif SC
    size:

  # Font settings for posts.
  posts:
    external: true
    size: 1.1

  # Font settings for <code> and code blocks.
  codes:
    external: true
    family: Inconsolata

sidebar:
  # Sidebar Position.
  position: right
  #position: right
  # Replace the default avatar image and set the url here.
  avatar: avatar.jpg


widgets:
  random_posts: false # æ˜¾ç¤ºéšæœºæ–‡ç« 
  recent_comments: false # æ˜¾ç¤ºæœ€è¿‘è¯„è®º


# é¡µå°¾å…¨ç«™ç»Ÿè®¡
footer:
  since: 2021
  icon:
    name: sakura rotate
    # Change the color of icon, using Hex Code.
    color: "#ffc0cb"
  count: true

# æ–‡ç« ç•Œé¢ç»Ÿè®¡
post:
  count: true

valine:
  appId: vqRVoPckA01cjMKK2VDQukUg-MdYXbMMI
  appKey: 2e07XB91LUSPnpSQziA1GUcu
  placeholder: ãƒ½(â—‹Â´âˆ€`)ï¾‰â™ª å‘ä¸€æ¡å‹å–„çš„è¯„è®º~  # Comment box placeholder
  avatar: mp # Gravatar style : mp, identicon, monsterid, wavatar, robohash, retro
  pageSize: 10 # Pagination size
  lang: zh-CN
  visitor: true # æ–‡ç« è®¿é—®é‡ç»Ÿè®¡
  NoRecordIP: false # ä¸è®°å½• IP
  serverURLs: https://vqrvopck.api.lncldglobal.com # When the custom domain name is enabled, fill it in here (it will be detected automatically by default, no need to fill in)
  powerMode: true # é»˜è®¤æ‰“å¼€è¯„è®ºæ¡†è¾“å…¥ç‰¹æ•ˆ
  tagMeta:
    visitor: æ–°æœ‹å‹
    master: åšå®¢ä½œè€…
    friend: å°ä¼™ä¼´
    investor: è‡­çŒªçŒªğŸ–
  tagColor:
    master: "var(--color-orange-old)"
    friend: "var(--color-aqua)"
    investor: "var(--color-blue)"
  tagMember:
    master:
      - 56167cb60097e1c973dc0b2070f8a9b1


      # - hash of master2@email.com
      # å±…ç„¶è¦ç”¨hashå€¼ï¼Œæˆ‘äººå‚»äº†
    friend:
      - 09a7ff9655c14dcf35c80d255c2ec152
        
      # - hash of friend@email.com
      # - hash of friend2@email.com
    investor:
      - 8bf2e597887a9b200b027ac49b254c5d
      # - hash of investor1@email.com
# å…³é—­æ‰“èµ
reward:
  # If true, reward will be displayed in every article by default.
  enable: false